image: php:7.3-cli-alpine

before_script:
    - export DEBIAN_FRONTEND=noninteractive

cache:
    paths:
        - vendor

stages:
    - test

phpcs:
    stage: test
    script:
        - wget https://github.com/FriendsOfPHP/PHP-CS-Fixer/releases/download/v2.13.1/php-cs-fixer.phar
        - php php-cs-fixer.phar fix --dry-run --diff
