image: php:7.2-cli-alpine

before_script:
    - export DEBIAN_FRONTEND=noninteractive

stages:
    - test

cache:
    paths:
        - vendor

phpunit:
    stage: test
    script:
        - wget https://raw.githubusercontent.com/composer/getcomposer.org/5eb0614d3fa7130b363698d3dca52c619b463615/web/installer -O - -q | php -- --quiet
        - php composer.phar install --no-progress --no-interaction --no-suggest
        - php vendor/bin/phpunit

phpcs:
    stage: test
    script:
        - wget https://github.com/FriendsOfPHP/PHP-CS-Fixer/releases/download/v2.13.1/php-cs-fixer.phar
        - php php-cs-fixer.phar fix --dry-run --diff
